wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.41290330657180263
epochs:
  value: 100
hidden_size:
  value: 256
learning_rate:
  value: 0.0006084976629979318
num_experts:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 5.995844598783594e-05
