wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3734835551482087
epochs:
  value: 100
hidden_size:
  value: 1024
learning_rate:
  value: 0.000211727840547364
num_experts:
  value: 8
optimizer:
  value: sgd
weight_decay:
  value: 1.6436563050820676e-05
