wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4737349636497551
epochs:
  value: 100
hidden_size:
  value: 512
learning_rate:
  value: 2.551844978158391e-05
num_experts:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.0009783574955497944
