_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 76
                - 77
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.4
            "6": 4.43.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 50
learning_rate:
    value: 0.0007080374771662529
optimizer:
    value: adam
weight_decay:
    value: 0.0002964864672626963
