_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 76
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 76
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.4
            "6": 4.43.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 32
dropout:
    value: 0.4737349636497551
epochs:
    value: 100
hidden_size:
    value: 512
learning_rate:
    value: 2.551844978158391e-05
num_experts:
    value: 3
optimizer:
    value: adam
weight_decay:
    value: 0.0009783574955497944
